lua/snacks/win.lua

Previously, backdrop windows were being created with the default border options set in `opts`. I can't imagine this is ever desirable (see screenshots), so always set the backdrop window border to none.
N/A

fix(win): set border to none for backdrop windows

---

doc/snacks-words.txt
docs/words.md
lua/snacks/words.lua

Add an opt-in option to show a notification for `Snacks.words.jump`, that displays the number and index of the current reference. The notification uses `Snacks.notify.info` to be consistent with the rest of the repo.

feat(words): `jump` optionally shows notification with reference count

---

docs/rename.md

Adds an example to `rename.md` for nvim-tree. 
I spent way too long obsessing over the way the code looked to make it feel like the other examples.
N/A

docs(rename): add nvim-tree example

---

lua/snacks/terminal.lua

1. Currently `gf` only search in current working directory. Use `**` in `findfile()` to do a recursive search. Otherwise, `gf` can't open a file down a nested directory.
2. `vim.schedule` the command `vim.cmd("e ", f)`, because otherwise it opens the file but goes to the buffer that was already opened. Not sure why this happens, but if we schedule it correctly goes to the opened buffer by `gf`.
3. Also changed `self:close()` to `self:toggle()`, so as not to reset the state of the terminal unless a user specifically exits the terminal. This is rather personal and also based on a [LazyVim Discussion](https://github.com/LazyVim/LazyVim/discussions/4741), but I can understand if it's not wanted in the scope of `snacks.nvim` and probably users could change the behavior of the `gf` key in their …

fix(terminal): `gf` properly opens file

---

README.md

Fixes "Rename File" keymap in Usage section of README.

docs(example): fix rename file keymap

---

lua/snacks/win.lua

The window position is not correctly centered when position is set to `float` and border isn't `none`. I found [a similar issue](https://github.com/folke/lazy.nvim/issues/812) in [lazy.nvim](https://github.com/folke/lazy.nvim) along with [your fix](https://github.com/folke/lazy.nvim/commit/451f217e9b2d71f08bdae0ce5ac7e8e8a6503f48) there, so I have applied the same fix here. Thank you for your work!
https://github.com/folke/lazy.nvim/issues/812

fix(win): take border into account for window position

---

lua/snacks/notifier.lua

`colorcolumn` should be disabled by default, since in most cases, the user will not want to have them displayed in a notification.
before:
after:

fix(notifier): disable `colorcolumn` by default

---

README.md
doc/snacks-init.txt
doc/snacks-statuscolumn.txt
docs/init.md
docs/statuscolumn.md
lua/snacks/docs.lua
lua/snacks/health.lua
lua/snacks/init.lua
lua/snacks/lazygit.lua
lua/snacks/notifier.lua
lua/snacks/statuscolumn.lua
lua/snacks/terminal.lua
lua/snacks/toggle.lua

With this change, plugins are no longer enabled by default.
The are enabled when passing any options for the plugin, or by explicitely setting `enabled = true`.
This PR also adds a bunch of healthchecks `:checkhealth snacks`

feat(config)!: plugins are no longer enabled by default. Pass any options, or set enabled = true

---

lua/snacks/notifier.lua

Don't put padding with no title and no icon, so that there is no gap in the border.
Fixes #84.

fix(notifier): no gap in border without title/icon

---

lua/snacks/win.lua

`vim.keymap.set` was missing the `nowait = true`

fix(win): delay when closing windows

---

README.md

Updated it because somebody place ! outside of the brackets :))
The big picture? Well, people can get lost because what does ![tip] mean compared to **<span style="background-color: green; border: 2px solid lightgreen">Tip</span>**?
It doesn't seem that there are any...

fix(docs): typo in README.md

---

lua/snacks/dashboard.lua

If `colorcolumn` is set, e.g.:
```lua
vim.opt.colorcolumn = { 80, 100 } -- Guide columns positions
```
The dashboard window shows the columns:
This PR add the missing window option

fix(dashboard): disable `vim.wo.colorcolumn`

---

lua/snacks/dashboard.lua

Firstly, thank you for integrating persisted.nvim in the dashboard out of the box.
This PR changes the command to load a persisted.nvim session. This accounts for users potentially not having `SessionLoad` available to them if they lazy load their dashboard and don't have `cmd = { "SessionLoad" }` setup.
N/A
N/A

refactor(dashboard): change persisted.nvim load session command

---

lua/snacks/gitbrowse.lua

The `remote` is used as a regex pattern, so the dot in the `"github.com"` means any character. This PR correct the regexes in default `url_patterns`.
https://github.com/folke/snacks.nvim/blob/aa38175c002555aded511b6787380ad887665680/lua/snacks/gitbrowse.lua#L40-L49
https://github.com/folke/snacks.nvim/blob/aa38175c002555aded511b6787380ad887665680/lua/snacks/gitbrowse.lua#L68-L72
Test code:
```lua
print(require("snacks").gitbrowse.get_url("https://githubacom.com/folke/snacks.nvim"))
```
**Before**
**After**

fix(gitbrowse): fix the regex in url_patterns

---

lua/snacks/gitbrowse.lua

`gitbrowse` opens commit when word under cursor is valid commit hash. Please check the Lua pattern for the commit hash in the validation function I used as I'm not confident as to if it covers all the cases. I only tested with `diffview` file history and `gitsigns` blame buffer as I don't use other tools.
Closes #138.

feat(gitbrowse): open commit when word is valid hash

---

lua/snacks/dashboard.lua

Set the dashboard buffer to not listed for consistency with other dashboard plugins

feat(dashboard): make buffer not listed

---

lua/snacks/dashboard.lua

Don't open dashboard when Neovim opens with only startup option args. Took a look at how `dashboard.nvim` did it.
They also have an autocmd for `StdInReadPre`, but I tested with piping `echo "hello" | nvim` and it works as expected.
Not sure if it's the best solution, so feel free to make any additional changes or completely disregard for something more robust.
Closes #221.

fix(dashboard): don't open with startup option args

---

lua/snacks/input.lua

1. Trim the trailing `:` from the prompt. The `:` is usually added to `vim.ui.input`, since it is by default displayed in the cmdline, where a separater is useful. As a window title, however, it serves no purpose; adding a `:` to a title is generally disrecommended.
2. Disable cursorline in the input window by default. Since the input window by default has a height of 1, the cursorline is not helpful at all, and only results in an inconsistently looking appearance. 
3. In case the user disables the icon by setting it to `""`, there is excess padding which looks weird (and also does not align with a window title set to `left`). Thus added a check for an empty string and adjust the padding accordingly.
4. Set `snacks_input` as default filetype for the input buffer, in line with how the …

fix(input): various minor visual fixes

---

lua/snacks/dashboard.lua

The intention is to make it easier to exclude the dashboard terminal from some plugins. For example, heirline.nvim sets winbar per-window to allow for winbar to be optionally disabled in non-floating windows, so this PR lets me disable heirline for snacks' dashboard terminals over other floating terminals.

fix(dashboard): add filetype to terminal sections

---

lua/snacks/input.lua

The new`icon_pos` /`title_pos` options resulted in a situation where there is missing padding when neither is positioned left. This PR fixes this by falling back to `" "` as statuscolumn.
before
after

fix(input): missing padding if neither title nor icon positioned left

---

lua/snacks/indent.lua

The lead listchar was not being honoured in https://github.com/folke/snacks.nvim/commit/0e150f5510e381753ddd18f29facba14716d5669, this pull request fixes that.
Fixes #291.
Before the fix:
After the fix:

fix(indent): honor lead listchar

---

lua/snacks/notifier.lua

Option to exclude some notifications from notification history,
for example, when dealing with spinners.

feat(notifier): `hide_from_history` option

---

lua/snacks/notifier.lua

This [commit](https://github.com/folke/snacks.nvim/commit/fd9ef30206185e3dd4d3294c74e2fd0dee9722d1) renamed the style for `history_notification`, but opening the window still used the old name.

fix(notifier): open history window with correct style

---

doc/snacks-dashboard.txt
docs/dashboard.md
docs/examples/dashboard.lua

When copying the "advanced" or "github" examples for dashboard, there was error 'hub is not recognized' changing ```hub status --short --branch --renames``` to ```git status --short --branch --renames``` fixes that

chore(dashboard): replace 'hub status' with 'git status'

---

lua/snacks/init.lua

To allow syntax like:
```lua
local mystyle = Snacks.config.style('...')
-- somewhere else
Snacks.win({
style = mystyle
})
```
and improve code navigation (e.g. jumping using `gd`, as opposed to searching string, or not being sure of the exact name, ...)

feat(styles): exportable styles

---

docs/examples/init.lua

Since https://github.com/folke/snacks.nvim/pull/89 was merged gitbrowse supports opening multiline URLs. 
This patch updates the keymap example docs to include visual mode so the feature works as expected.

chore(docs): updated gitbrowse keymap to support visual mode

---

lua/snacks/win.lua

`backdrop` displays a bright cell at the top left. upon investigation, I figured out that it's created by the user's `colorcolumn` setting also being applied to the backdrop.
Disable `colorcolumn` for the backdrop window.
before
after

fix(win): backdrop having bright cell at top right

---

lua/snacks/lazygit.lua

Using boolean value inside `config` resulted in error `attempt to concatenate a boolean value` inside `to_yaml` function.
This PR fixes it by converting boolean values to string
Example config:
```
lazygit = {
config = {
gui = {
showFileTree = false,
},
},
},
```

fix(lazygit): enable boolean values in config

---

lua/snacks/dashboard.lua

This change hashes the caching key for snacks dashboards terminal sections instead of building the key from the command itself. This allows for arbitrary length scripts to be given as a terminal section command instead of relying on existing commands in PATH. 
#379

fix(dashboard): hash dashboard terminal section caching key to support long commands

---

lua/snacks/input.lua

I'm suspect this was just a typo... using the border highlight group rather than title.

fix(input): use correct highlight group for input prompt

---

lua/snacks/scratch.lua

When toggling scratch closed, it's possible for the active buffer to be something other than the scratch buffer.
This results in the autowrite behaviour triggering a `write` for whatever that active buffer was and leaving the scratch buffer as dirty.
- Fixes #449.

fix(scratch): autowrite right buffer. Fixes #449.

---

lua/snacks/picker/source/git.lua

Cwd was wrong for git status picker.
- Fixes #504

fix(picker): set correct cwd for git status picker

---

lua/snacks/picker/config/defaults.lua
lua/snacks/picker/config/sources.lua
lua/snacks/picker/preview.lua
lua/snacks/picker/source/git.lua

Hi and thank you for the useful plugin!
I have been exploring the new picker api and got this git diff picker working which I think can be a nice addition to the existing set of picker. The key difference from the existing git_status picker is that it separates each hunk into its own item similar to `git add --patch` and when you select an item it takes you to the first hunk's line instead of top of the buffer. Before I put more effort into it I would like to see if this is a welcome change first.
This implementation can be further extended by allowing to support additional arguments such as `--staged`, `--ignore-all-space` or both.
A few points on current implementations. I could not get the per line parsing to work using the `require("snacks.picker.source.proc").proc(...)` and fell back …

feat(picker.git_diff): pick diff hunks

---

lua/snacks/bigfile.lua

In my config I use the following flag to disable the default `MatchParen` plugin.
```
vim.g.loaded_matchparen = 1
```
This causes an error when `bigfile` tries to call the `NoMatchParen` command since it does not exist.
This PR fixes that by checking for the existence of the command before executing it.

fix(bigfile): check existence of NoMatchParen before executing

---

lua/snacks/picker/source/git.lua

When new folder is created in a git project, and there are files inside, git status picker only shows the folder without any preview. Adding `-uall` to the commands lists them all.
Before: 
After:

fix(picker): show all files in git status

---

lua/snacks/picker/config/defaults.lua
lua/snacks/picker/config/highlights.lua
lua/snacks/picker/core/list.lua
lua/snacks/picker/format.lua

Snacks picker allows setting an icon for selected list entries.
With this PR, we can also select one for unselected entries.
I think it looks great.
(Replica of #583 which I closed by mistake, sorry about that.)

feat(picker): custom icon for unselected entries

---

lua/snacks/zen.lua

The cursor position is now synchronized between the zen/zoom window and it's parent.
I'm not sure if this is the best way to achieve that. Initally I wanted to do set the parent's cursor position only when the zen buffer is closed, but I couldn't figure out a way to do that. 
Fixes #539

fix(zen): sync cursor with parent window

---

lua/snacks/statuscolumn.lua

- https://github.com/folke/snacks.nvim/commit/d972bc0a471fbf3067a115924a4add852d15f5f0 breaks cache key for virtual lines since `0 and 1 or 0` also evaluates to 1 in lua.
- Fixes #510

fix(statusline): fix status line cache key

---

lua/snacks/input.lua

When the input opens, the cursor is placed two columns to the right after the default prompt, but should be one.
The cause is the `vim.api.nvim_win_set_cursor` takes (row, col) with the base of (1, 0) */I hate this/*
No related issue created.
`:lua Snacks.input({ default = "aaa" }, function () end )`
gives the input as "aaa |" (where pipe shows the cursor position)

fix(input): put the cursor right after the default prompt

---

lua/snacks/picker/actions.lua
lua/snacks/picker/config/highlights.lua
lua/snacks/picker/format.lua
lua/snacks/picker/preview.lua
lua/snacks/picker/source/git.lua

Handle [detached HEAD](https://git-scm.com/docs/git-checkout#_detached_head)
- list: display correct information
- preview: without error notification
- action: checkout the commit that HEAD detached at
- Fixes #672 
Before:
After:

fix(picker.git_branches): handle detached HEAD

---

lua/snacks/picker/actions.lua
lua/snacks/picker/config/sources.lua

This enables the ability to delete buffers directly from the `smart` picker (or other combined pickers) by adding a check + warning to the `bufdelete` action (ensuring it only operates on buffer items), and adding the same `dd` and `<c-x>` mappings as the `buffers` picker.
TBD... searching.
https://github.com/user-attachments/assets/6c5c4b5e-74ed-4778-9f31-a714f7da1853

feat(picker.smart): add bufdelete actions from buffers picker

---

lua/snacks/picker/actions.lua
lua/snacks/picker/config/defaults.lua
lua/snacks/win.lua

This is an initial commit for trying to add horizontal scrolling for the picker preview window.
Known issue: when scrolling horizontally with scope indent, the indent chars persist in the preview window and  don't disappear as they should...
Edit:
I just realized this happens only when we are previewing a buffer that is already open. Only in that case the indents are being rendered... if we are previewing a file that is not currently open the indents don't get rendered and therefore there is no issue. Maybe this is a bug? Should we prevent rendering of the indent guides in the preview window? 
- Fixes #676

feat(picker): preview window horizontal scrolling

---

lua/snacks/picker/config/sources.lua

This PR adds 2 actions to the `keymaps` picker, to toggle the `global` and `local` options.
None.
https://github.com/user-attachments/assets/3f4ca80a-b554-47a2-970b-15dc84f357d8

feat(picker.keymaps): add global + buffer toggles

---

lua/snacks/picker/source/icons.lua

Thanks for the icons picker 🙇🏼 
I had one in my dotfiles I was going to contribute, but you have been faster.
So there it is, I added some things I had in mine
This PR:
- fix a typo in the Nerd Fonts source name (its plural)
- add The category full names to be consistent with emojis
> [!NOTE]
> Would you be interested in some extra sources I was working on ? At least Math and Box drawing ?
> [!NOTE]
> I would also switch the name the source so Source can be capitalize like the Category and I think having Source > Category after is easier to read as the glyph and the icons are actuelly what people search. But this is personal taste, sp I did not submnitted this change

fix(picker.icons): fix typo in Nerd Fonts and display the full category name

---

lua/snacks/bufdelete.lua

`vim.fn.confirm` don't return 3 on ctrl-c, but throw an error.
```
E5108: Error executing lua Keyboard interrupt
```

fix(bufdelete): ctrl-c throw error in `fn.confirm`

---

lua/snacks/picker/core/filter.lua

Here we see that we insert the paths into `filter` instead of `self.paths` https://github.com/folke/snacks.nvim/blob/b96bd540f785c725289f9f15f0147b1b2dac5a35/lua/snacks/picker/core/filter.lua#L34-L44
and later on here https://github.com/folke/snacks.nvim/blob/b96bd540f785c725289f9f15f0147b1b2dac5a35/lua/snacks/picker/core/filter.lua#L90-L94 we check `self.paths` to get the path.
This was causing issues to not correctly filter out the already defined paths and I was able to see, for example the scratch buffer files in the pickers.
None

fix(filter): insert path from `filter.paths` into `self.paths`

---

lua/snacks/picker/core/picker.lua

`Picker.resume` sometimes get an error:
```
Error executing vim.schedule lua callback: ...zy_178550383/snacks.nvim/lua/snacks/picker/core/list.lua:183: attempt to index field 'picker' (a nil value)
stack traceback:
...zy_178550383/snacks.nvim/lua/snacks/picker/core/list.lua:183: in function '_move'
...zy_178550383/snacks.nvim/lua/snacks/picker/core/list.lua:203: in function 'move'
...zy_178550383/snacks.nvim/lua/snacks/picker/core/list.lua:100: in function 'view'
..._178550383/snacks.nvim/lua/snacks/picker/core/picker.lua:341: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
1. `Snacks.picker.grep({live=false, search='a'})`.   ##  run in a big repro
2. close picker immediately before `rg` stops running
3. run `resume`
4.  close picker and get an error

fix(picker.resume): fix picker is nil

---

lua/snacks/dashboard.lua

When `picker` is enabled, the original line removes it from the table and reinserts it as the first element, preventing the user configuration in `preset.picker` from being used as the picker. This change inserts it as the second element instead.

fix(dashboard): don't override user configuration

---

lua/snacks/win.lua

`vim.split` would split `""` into `{ "" }`, causing `table.concat` to output `",eol: "`.
Resolved by using `vim.tbl_filter` to filter out empty strings before applying `table.concat`.

fix(win): error when enabling padding with `listchars=""`

---

.gitignore
lua/snacks/layout.lua
lua/snacks/picker/actions.lua
lua/snacks/picker/config/defaults.lua
lua/snacks/picker/config/highlights.lua
lua/snacks/picker/config/init.lua
lua/snacks/picker/config/sources.lua
lua/snacks/picker/core/actions.lua
lua/snacks/picker/core/input.lua
lua/snacks/picker/core/list.lua
lua/snacks/picker/core/picker.lua
lua/snacks/picker/core/score.lua
lua/snacks/picker/format.lua
lua/snacks/picker/init.lua
lua/snacks/picker/source/buffers.lua
lua/snacks/picker/source/explorer.lua
lua/snacks/picker/source/files.lua
lua/snacks/picker/source/lsp.lua
lua/snacks/picker/source/snacks.lua
lua/snacks/picker/source/vim.lua
lua/snacks/rename.lua

File explorer picker.
```lua
{
{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
{
"folke/snacks.nvim",
keys = {
{ "<leader>e", function() Snacks.picker.explorer() end, desc = "Explorer Snacks" },
},
init = function()
vim.api.nvim_create_autocmd("BufEnter", {
group = vim.api.nvim_create_augroup("snacks_explorer_start_directory", { clear = true }),
desc = "Start Snacks Explorer with directory",
once = true,
callback = function()
local dir = vim.fn.argv(0) --[[@as string]]
if dir ~= "" and vim.fn.isdirectory(dir) == 1 then
Snacks.picker.explorer({ cwd = dir })
end
end,
})
end,
},
}
```

feat(picker): new file explorer `Snacks.picker.explorer()`

---

lua/snacks/picker/actions.lua

This PR addresses an issue where the quickfix list (qflist) would open on the left side of the screen when using vertical splits. By replacing the default :copen command with :botright copen, this update ensures that the qflist consistently opens at the bottom, regardless of the current window layout.
1. Open Neovim: Start Neovim normally.
2. Create a Vertical Split
3. Use picker to pick anything
4. Press <c-q> to send them to quickfix list
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
vim.g.mapleader = " "
require("lazy.minit").repro({
spec = {
{
"Isrothy/snacks.nvim",
branch = "bottom-positioning-for-qf",
lazy = false,
keys = {
{
"<LEADER>ff",
function()
Snacks.picker.files()
end,
desc = …
```

fix(picker): enforce bottom positioning for quickfix and location lists

---

lua/snacks/picker/actions.lua
lua/snacks/picker/source/vim.lua

Currently when you use picker.commands to select a command that requires an argument, it will cause an error. `:BlickCmd` is one example. To avoid the error we can feed the keys to enter the command mode and populate the command and leave it to the user what they want to do. 
This is also what telescope [does](https://github.com/nvim-telescope/telescope.nvim/blob/415af52339215926d705cccc08145f3782c4d132/lua/telescope/builtin/__internal.lua#L399) in its builtin command picker.
nargs values `*` or `?` mean that the command can be executed both with arguments and without. I think it is safer to leave it to the user to decide if they want them to either trigger a run or provide the arguments. But happy to change it if you think running the commands by default makes sense.

feat(picker.commands): do not autorun commands that require arguments

---

lua/snacks/picker/actions.lua

A minor update to add a confirmation dialogue before deleting a branch in `git_branches`.

feat(picker): add confirmation before deleting a git branch

---

lua/snacks/scope.lua

Adding a config flag to allow injected languages to be parsed by treesitter. This is crucial for languages like vue, which contain typescript or javascript in a script tag. When `treesitter.get_node` is not called with ignore_injections = false, the script tag is treated as a single block, which is not helpful, as it contains most code for languages like vue.
- Fixes #430 
- See #430

feat(scope): allow injected languages to be parsed by treesitter

---

docs/rename.md

Add an autocmd for oil.nvim integration of snacks.rename to the docs, similar to mini.files.

docs(rename): add oil.nvim integration

---

lua/snacks/picker/source/files.lua

Fix the icon for `Snacks.picker.zoxide()`.
None.
Before:
After:

fix(picker.zoxide): directory icon

---

lua/snacks/gitbrowse.lua

`Snacks.gitbrowse({ what = "permalink" })` got following error when `vim.fn.getcwd()` is not a git repository or not the git repository of current file:
```
E5108: Error executing lua ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/gitbrowse.lua:137: ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/gitbrowse.lua:117: __ignore__
stack traceback:
[C]: in function 'error'
...cal/share/nvim/lazy/snacks.nvim/lua/snacks/gitbrowse.lua:137: in function 'gitbrowse'
[string ":lua"]:1: in main chunk
Failed to get latest commit of file
fatal: not a git repository (or any of the parent directories): .git
```
- Fixes #320
- Related #438
None.

fix(gitbrowse): cwd for permalinks

---

lua/snacks/statuscolumn.lua

Currently, clicking the status column on a line without a fold results in an error (see screenshot below). This PR adds a check before executing `za` to prevent this issue.

fix(statuscolumn): only execute `za` when fold exists

---

lua/snacks/picker/config/sources.lua
lua/snacks/picker/source/treesitter.lua

Adds a `opts.tree` boolean option for treesitter picker to toggle on/off tree symbols
None, rather a discussion #1101

feat(treesitter): add `tree` boolean to toggle on/off tree symbols

---

lua/snacks/toggle.lua

Allows user to add custom which-key description in the `toggle` itself
Closes #1114

feat(toggle): allow user to add custom which-key description

---

lua/snacks/gitbrowse.lua

The previous logic didn't check for `fields.commit` when checking whether to switch to `branch` or `repo`, thus `opts.what = "commit"` was always being overwritten.
None

fix(gitbrowse): previous logic always overwrote 'commit'

---

lua/snacks/picker/source/lsp/init.lua

this adds an attribute for the range of the LSP symbol to each picker item.
Fixes #1057 
having access to the range of the LSP symbol (i.e. the whole context of classes and methods) would be tremendously helpful for my solution in https://github.com/folke/snacks.nvim/issues/1057#issuecomment-2652052218. Currently the picker items only have a `loc` attribute which holds the range of the symbol identifier, i.e. the class/method name.
---
perhaps in a followup we could use the range to highlight the symbol context, similar to how trouble.nvim does it

feat(picker): add LSP symbol range to result item

---

lua/snacks/picker/select.lua

From the docs on `:help vim.ui.select`
```
• {on_choice}  (`fun(item: any?, idx: integer?)`) Called once the user
made a choice. `idx` is the 1-based index of `item`
within `items`. `nil` if the user aborted the dialog.
```
Right now the behavior will call `on_choice` if the user confirmed a selection, but will not be called at all if the user explicitly or implicitly closes the picker. As a plugin author, I rely on the guarantee that if I call `vim.ui.select`, the callback _will_ be called either with a value or with a nil.
I just added the simplest, dumbest possible fix for this that prevents double-calling the callback.
N/A
N/A

fix(picker): vim.ui.select callback is called when canceling selection

---

lua/snacks/picker/source/explorer.lua

`opts.diagnostics=false` was being ignored by `Snacks.picker.explorer`
I didn't create an issue for it

fix(picker.explorer): ensure diagnostics can be disabled

---

lua/snacks/input.lua

Add the missing highlight group for input title.
Before:
After:

fix(input): add missing hl group for input title

---

lua/snacks/image/init.lua

**Problem**: Sometimes when entering Insert mode, I would get an error message from image's `attach` function:
```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/image/doc.lua:215: scoped variable: Invalid buffer id: 88
stack traceback:
[C]: in function '__index'
...cal/share/nvim/lazy/snacks.nvim/lua/snacks/image/doc.lua:215: in function 'attach'
...al/share/nvim/lazy/snacks.nvim/lua/snacks/image/init.lua:174: in function <...al/share/nvim/lazy/snacks.nvim/lua/snacks/image/init.lua:173>
```
Looks like by the time the `attach` function is called, the buffer is no longer valid. This is caused by using `vim.schedule`, which introduces a small delay, during which the buffer can be deleted.
I suspect this is related to blink.cmp, but I cannot tell for …

fix(image): do not attach to invalid buffers

---

lua/snacks/picker/config/sources.lua

When using the git log sources, what are your thoughts on preserving the sort order when matching? I find most often when I use this picker I want to see results in reverse chronological order. For example, I like to use the picker to review the commit log to see new features added to a repo.
When matching for `feat` in the snacks repo with current behavior, the output is less than useful:
But with the proposed change, it's much more relevant:
I can override in my config:
```lua
picker = {
sources = {
git_log = { sort = { fields = { "score:desc", "idx" } } },
git_log_file = { sort = { fields = { "score:desc", "idx" } } },
git_log_line = { sort = { fields = { "score:desc", "idx" } } },
},
},
```

fix(picker.git): preserve chronological order when matching

---

lua/snacks/dashboard.lua

I have 5000 oldfiles, every time i go to a new directory and open nvim, the dashboard recent_files (with `cwd=true`) computation takes 4-5 seconds to go through all oldfiles before deciding nothing should show up
```lua
sections = {
{ icon = " ", title = "Recent files (current directory)", section = "recent_files", cwd = true },
}
```
It appears to be the `vim.v.oldfiles[i]` indexing. I didn't look much into it but it opens much faster looping with ipairs.
Repro:
1. add the above section config in dashboard
2. increase oldfiles limit and populate up to the limit
3. `mkdir brand-new-directory; cd brand-new-directory; nvim`
4. the section is empty as expected, but it takes a few seconds before dashboard shows up

perf(dashboard): speed up filtering for recent_files

---

lua/snacks/words.lua

This allows user to specify explicitly filetypes to disable `snacks.words`.
Closes #1294

feat(words): add `filter` function for user to disable specific filetypes

---

lua/snacks/image/doc.lua

Tall inline typst equations were previously cropped too much vertically. The change to the template now resize text frames to the bounding box of their glyphs. See https://typst.app/docs/reference/text/text/#parameters-top-edge for more details.
Before:
After:

fix(image.doc): crop inline typst equations properly

---

lua/snacks/zen.lua

Zen window height should always account for `cmdheight` (not only if `statusline` is enabled) and be computed dynamically when `cmdheight > 0` to avoid the `cmdline` obstructing the Zen window.
- Fixes https://github.com/folke/snacks.nvim/issues/1401
- Fixes https://github.com/folke/snacks.nvim/issues/1375
Before: ![zen-mode-cmdline](https://github.com/user-attachments/assets/c03be4af-2368-4b04-8065-49ced875aa2d)
After: ![zen-mode-fixed-cmdline](https://github.com/user-attachments/assets/14dc72bb-7431-4d05-b0fd-b6a2367bdc6d)

fix(zen): always count cmdheight towards Zen bottom offset

---

.gitignore
tests/image/test.aux
tests/image/test.tex

Current test.tex page is poorly written and often contains mistakes (e.g. missing backspace in front of greek letters). I have created a page that is much more useful. It contains some of the most beautiful math equations ever written. The file is validated: "pdflatex test.tex" command produces valid (and nice looking) PDF document.
The document is also much longer - I have some issues with it in nvim (partial latex rendering or rendering that works only if something major is changed), so maybe it can help Folke to check the latex preview functionality once again.

test(image): better latex test document
